version: "3"

tasks:
  generate:
    aliases:
      - go
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/**/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generate-rust:
    aliases:
      - rust
    desc: "Generate Rust code from proto files using prost"
    cmds:
      - protoc -I proto proto/auth/auth.proto proto/metrics/metrics.proto --rust_out=.\gen\rust --rust_opt=experimental-codegen=enabled --tonic_out=.\gen\rust
